// Rebuilds admin.enc.js from _private/traditions.json (which is gitignored).
//   node tools/encode.js
// XOR with the gate word + base64. This hides the list from a casual view-source,
// nothing more: it is obfuscation, not security.
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const KEY = Buffer.from('konami');
const src = fs.readFileSync(path.join(root, '_private', 'traditions.json'));
JSON.parse(src); // fail loudly on bad JSON
const out = Buffer.alloc(src.length);
for (let i = 0; i < src.length; i++) out[i] = src[i] ^ KEY[i % KEY.length];
fs.writeFileSync(path.join(root, 'admin.enc.js'),
  '// Generated by tools/encode.js — do not edit by hand.\nwindow.ADMIN_BLOB = "' + out.toString('base64') + '";\n');
console.log('admin.enc.js written,', src.length, 'bytes');
